<?php

$labels = array();
$labels['initials'] = 'Inicjały';
$labels['profession'] = 'Zawód';
$labels['officelocation'] = 'Adres biura';
$labels['children'] = 'Dzieci';
$labels['pgppublickey'] = 'Klucz publ. PGP';
$labels['freebusyurl'] = 'URL Free-busy';
$labels['settings'] = 'Ustawienia';

$labels['addressbookprio'] = 'Wybór/zachowanie książek adresowych';
$labels['personalfirst'] = 'Najpierw osobiste książki adresowe';
$labels['globalfirst'] = 'Najpierw globalne książki adresowe';
$labels['personalonly'] = 'Tylko osobiste książki adresowe';
$labels['globalonly'] = 'Tylko globalne książki adresowe';

?>
