<?php

$labels = array();

$labels['tabtitle'] = 'Delegation';
$labels['delegates'] = 'Delegates';
$labels['delegate'] = 'Delegate';
$labels['mail'] = 'Email';
$labels['contact'] = 'Address Books';
$labels['event'] = 'Calendars';
$labels['task'] = 'Tasks';
$labels['note'] = 'Notes';

$labels['adddelegate'] = 'Add delegate';
$labels['deletedelegate'] = 'Delete delegate';

$labels['savingdata'] = 'Saving data...';
$labels['delegatedeleteconfirm'] = 'Do you really want to delete this delegate?';
$labels['deletesuccess'] = 'The delegate was successfully removed.';
$labels['deleteerror'] = 'Could not remove delegate.';
$labels['updatesuccess'] = 'The delegate was successfully updated.';
$labels['updateerror'] = 'Could not update delegate.';
$labels['createsuccess'] = 'The delegate was successfully added.';
$labels['createerror'] = 'Could not add delegate.';

?>
