<?php

$labels = array();

$labels['tabtitle'] = 'Delegation';
$labels['delegates'] = 'Wydelegowani';
$labels['delegate'] = 'Delegate';
$labels['mail'] = 'Email';
$labels['contact'] = 'Address Books';
$labels['event'] = 'Calendars';
$labels['task'] = 'Tasks';
$labels['note'] = 'Notes';
$labels['yes'] = 'Yes';
$labels['no'] = 'No';

$labels['adddelegate'] = 'Add delegate';
$labels['deletedelegate'] = 'Delete delegate';

$labels['savingdata'] = 'Zapisuję dane...';
$labels['delegatedeleteconfirm'] = 'Do you really want to delete this delegate?';
$labels['delegateremoveacl'] = 'remove access rights on folders assigned to this user';
$labels['deleteconfirm'] = 'Confirmation';
$labels['deletesuccess'] = 'The delegate was successfully removed.';
$labels['deleteerror'] = 'Could not remove delegate.';
$labels['updatesuccess'] = 'The delegate was successfully updated.';
$labels['updateerror'] = 'Could not update delegate.';
$labels['createsuccess'] = 'The delegate was successfully added.';
$labels['createerror'] = 'Could not add delegate.';

?>
