<?php

$labels = array();

$labels['tabtitle'] = 'Делегирование';
$labels['delegates'] = 'Представители';
$labels['delegate'] = 'Представитель';
$labels['mail'] = 'Почта';
$labels['contact'] = 'Адресные книги';
$labels['event'] = 'Календари';
$labels['task'] = 'Задачи';
$labels['note'] = 'Заметки';
$labels['yes'] = 'Да';
$labels['no'] = 'Нет';

$labels['adddelegate'] = 'Добавить представителя';
$labels['deletedelegate'] = 'Исключить из представителей';

$labels['savingdata'] = 'Сохранение данных...';
$labels['delegatedeleteconfirm'] = 'Вы действительно хотите исключить этого пользователя из представителей?';
$labels['delegateremoveacl'] = 'удалить права на доступ к каталогам назначенные этому пользователю';
$labels['deleteconfirm'] = 'Подтверждение';
$labels['deletesuccess'] = 'Пользователь успешно исключён из представителей.';
$labels['deleteerror'] = 'Не удалось исключить представителя.';
$labels['updatesuccess'] = 'Представитель был успешно обновлён.';
$labels['updateerror'] = 'Не удалось обновить представителя.';
$labels['createsuccess'] = 'Представитель успешно добавлен.';
$labels['createerror'] = 'Не удалось добавить представителя.';

?>
