<?php
$labels = array();

// preferences
$labels['default_view'] = 'Default view';
$labels['time_format'] = 'Time format';
$labels['timeslots'] = 'Timeslots per hour';
$labels['first_day'] = 'First weekday';
$labels['add_category'] = 'Add category';
$labels['remove_category'] = 'Remove category';
$labels['add_calendar'] = 'Add calendar';
$labels['remove_calendar'] = 'Remove calendar';

// calendar
$labels['calendar'] = 'Calendar';
$labels['calendars'] = 'Calendars';
$labels['category'] = 'Category';
$labels['categories'] = 'Categories';
$labels['createcalendar'] = 'Create new calendar';
$labels['day'] = 'Day';
$labels['week'] = 'Week';
$labels['month'] = 'Month';
$labels['new_event'] = 'New event';
$labels['edit_event'] = 'Edit event';
$labels['edit'] = 'Edit';
$labels['save'] = 'Save';
$labels['remove'] = 'Remove';
$labels['cancel'] = 'Cancel';
$labels['title'] = 'Summary';
$labels['description'] = 'Description';
$labels['all-day'] = 'all-day';
$labels['export'] = 'Export to ICS';
$labels['location'] = 'Location';
$labels['date'] = 'Date';
$labels['start'] = 'Start';
$labels['end'] = 'End';
$labels['choose_date'] = 'Choose date';
$labels['freebusy'] = 'Show as';
$labels['free'] = 'Free';
$labels['busy'] = 'Busy';
$labels['outofoffice'] = 'Out of Office';
$labels['priority'] = 'Priority';
$labels['alarms'] = 'Reminder';
$labels['generated'] = 'generated at';
$labels['selectdate'] = 'Select date';
$labels['prev_year'] = 'Previous year';
$labels['prev_month'] = 'Previous month';
$labels['next_year'] = 'Next year';
$labels['next_month'] = 'Next month';
$labels['choose_date'] = 'Choose date';

$labels['showmessage'] = 'Message';
$labels['byemail'] = 'E-mail';
$labels['ondate'] = 'on date';
$labels['minutesbefore'] = 'minutes before';
$labels['hoursbefore'] = 'hours before';
$labels['daysbefore'] = 'days before';
$labels['minutesafter'] = 'minutes after';
$labels['hoursafter'] = 'hours after';
$labels['daysafter'] = 'days after';
$labels['addalarm'] = 'add alarm';

$labels['tabsummary'] = 'Summary';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattendees'] = 'Participants';
$labels['tabattachments'] = 'Attachments';

// messages
$labels['deleteventconfirm'] = "Do you really want to delete this event?";
$labels['errorsaving'] = "Failed to save changes";
$labels['operationfailed'] = "The requested operation failed";

// recurrence form
$labels['frequency'] = 'Repeat';
$labels['never'] = 'never';
$labels['daily'] = 'daily';
$labels['weekly'] = 'weekly';
$labels['monthly'] = 'monthly';
$labels['yearly'] = 'annually';
$labels['every'] = 'Every';
$labels['days'] = 'day(s)';
$labels['weeks'] = 'week(s)';
$labels['months'] = 'month(s)';
$labels['years'] = 'year(s) in:';
$labels['bydays'] = 'On';
$labels['until'] = 'the';
$labels['each'] = 'Each';
$labels['onevery'] = 'On every';
$labels['forever'] = 'forever';
$labels['recurrencend'] = 'Until';
$labels['forntimes'] = 'for $nr time(s)';
$labels['first'] = 'first';
$labels['second'] = 'second';
$labels['third'] = 'third';
$labels['fourth'] = 'fourth';
$labels['last'] = 'last';
$labels['dayofmonth'] = 'Day of month';

?>