<?php

$labels = array();

$labels['folderctype'] = 'Ordnerinhalt';
$labels['foldertypemail'] = 'E-Mail';
$labels['foldertypeevent'] = 'Kalender'; // Termine?
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Aufgaben';
$labels['foldertypenote'] = 'Notizen';
$labels['foldertypecontact'] = 'Kontakte';
$labels['foldertypeconfiguration'] = 'Konfiguration';

$labels['default'] = 'Standard';
$labels['inbox'] = 'Posteingang';
$labels['drafts'] = 'Entwürfe';
$labels['sentitems'] = 'Gesendet';
$labels['outbox'] = 'Postausgang';
$labels['wastebasket'] = 'Gelöscht';
$labels['junkemail'] = 'Spam';

$messages['defaultfolderexists'] = 'Es existiert bereits ein Standardordner für den angegebenen Typ';

?>
