<?php

$labels = array();

$labels['folderctype'] = 'Type de contenu';
$labels['foldertypemail'] = 'Courriel';
$labels['foldertypeevent'] = 'Calendrier'; // Events?
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Tâches';
$labels['foldertypenote'] = 'Notes';
$labels['foldertypecontact'] = 'Contacts';
$labels['foldertypeconfiguration'] = 'Configuration';
$labels['foldertypefile'] = 'Fichiers';
$labels['foldertypefreebusy'] = 'Disponible/Occupé';

$labels['default'] = 'Par Défaut';
$labels['inbox'] = 'Courrier entrant';
$labels['drafts'] = 'Brouillons';
$labels['sentitems'] = 'Envoyés';
$labels['outbox'] = 'Courrier sortant';
$labels['wastebasket'] = 'Corbeille';
$labels['junkemail'] = 'Indésirables';

$messages['defaultfolderexists'] = 'Il existe déjà un répertoire par défaut pour le type spécifié';

?>
