<?php

$labels = array();

$labels['folderctype'] = 'Inhoudstype';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Agenda'; // Events?
$labels['foldertypejournal'] = 'Dagboek';
$labels['foldertypetask'] = 'Taken';
$labels['foldertypenote'] = 'Notities';
$labels['foldertypecontact'] = 'Adresboek';
$labels['foldertypeconfiguration'] = 'Configuratie';
$labels['foldertypefile'] = 'Bestanden';
$labels['foldertypefreebusy'] = 'Free/Busy';

$labels['default'] = 'Standaard';
$labels['inbox'] = 'Inbox';
$labels['drafts'] = 'Concepten';
$labels['sentitems'] = 'Verzonden';
$labels['outbox'] = 'Te versturen';
$labels['wastebasket'] = 'Prullenbak';
$labels['junkemail'] = 'Ongewenst';

$messages['defaultfolderexists'] = 'Er is reeds een standaard map voor dit type inhoud';

?>
