<?php

$labels = array();
$labels['folderctype'] = 'Zawartość';
$labels['foldertypemail'] = 'Poczta';
$labels['foldertypeevent'] = 'Kalendarz';
$labels['foldertypejournal'] = 'Dziennik';
$labels['foldertypetask'] = 'Zadania';
$labels['foldertypenote'] = 'Notatki';
$labels['foldertypecontact'] = 'Kontakty';
$labels['default'] = 'Domyślny';
$labels['inbox'] = 'Odebrane';
$labels['drafts'] = 'Szkice';
$labels['sentitems'] = 'Wysłane';
$labels['outbox'] = 'Wychodzące';
$labels['wastebasket'] = 'Kosz';
$labels['junkemail'] = 'Spam';

?>
