<?php

$labels = array();

$labels['folderctype'] = 'Тип ящика';
$labels['foldertypemail'] = 'Почта';
$labels['foldertypeevent'] = 'Календарь'; // Events?
$labels['foldertypejournal'] = 'Журнал';
$labels['foldertypetask'] = 'Задачи';
$labels['foldertypenote'] = 'Заметки';
$labels['foldertypecontact'] = 'Контакты';
$labels['foldertypeconfiguration'] = 'Настройки';
$labels['foldertypefile'] = 'Файлы';
$labels['foldertypefreebusy'] = 'Занят/Свободен';

$labels['default'] = 'По умолчанию';
$labels['inbox'] = 'Входящие';
$labels['drafts'] = 'Черновики';
$labels['sentitems'] = 'Отправленные';
$labels['outbox'] = 'Исходящие';
$labels['wastebasket'] = 'Корзина';
$labels['junkemail'] = 'Спам';

$messages['defaultfolderexists'] = 'Уже назначен ящик по умолчанию для указанного типа';

?>
