<?php

$labels = array();
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Périphériques';
$labels['devicealias'] = 'Nom du Périphérique';
$labels['syncmode'] = 'Mode de synchronisation';
$labels['modeauto'] = 'Choix automatique';
$labels['modeflat'] = 'Forcer le mode à plat';
$labels['modefolder'] = 'Forcer le mode dossier';
$labels['synchronize'] = 'Synchroniser';
$labels['withalarms'] = 'Avec alarmes';
$labels['syncsettings'] = 'Paramètres de synchronisation';
$labels['deviceconfig'] = 'Configuration du périphérique';
$labels['folderstosync'] = 'Dossiers à synchroniser';
$labels['mail'] = 'Adresse de messagerie';
$labels['contact'] = 'Carnet d\'adresses';
$labels['event'] = 'Agendas';
$labels['task'] = 'Tâches';
$labels['note'] = 'Notes';
$labels['configuration'] = 'Configuration';
$labels['deletedevice'] = 'Supprimer ce périphérique';
$labels['imageformat'] = 'Format d\'image';
$labels['laxpiclabel'] = 'Autoriser les images PNG et GIF';
$labels['nodevices'] = 'Il n\'y a actuellement pas de périphérique enregistrés.<br/><br/>Pour enregistrer un périphérique, merci de d\'abord le connecter au serveur, en suivant <a href="http://wiki.kolab.org/Setup_ActiveSync">les instructions sur le Wiki</a>. Ensuite le périphérique sera accessible ici pour sa configuration.';
$labels['savingdata'] = 'Enregistrer...';
$labels['savingerror'] = 'Échec de l\'enregistrement de la configuration';
$labels['notsupported'] = 'Votre serveur ne supporte pas les métadonnées ou les annotations';
$labels['devicedeleteconfirm'] = 'Voulez-vous vraiment supprimer la configuration de ce périphérique?';
$labels['successfullydeleted'] = 'La configuration de ce périphérique a été supprimée';
$labels['devicenotfound'] = 'Impossible de lire la configuration du périphérique';

?>
