<?php

$labels = array();
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Devices';
$labels['devicealias'] = 'Device name';
$labels['syncmode'] = 'Synchronizatie modus';
$labels['modeauto'] = 'Stel automatisch vast';
$labels['modeflat'] = 'Forceer vlakke modus';
$labels['modefolder'] = 'Forceer mappen modus';
$labels['synchronize'] = 'Synchronizeren';
$labels['withalarms'] = 'Met alarmen';
$labels['syncsettings'] = 'Synchronizatie instellingen';
$labels['deviceconfig'] = 'Device configration';
$labels['folderstosync'] = 'Folders to synchronize';
$labels['mail'] = 'Email';
$labels['contact'] = 'Adresboeken';
$labels['event'] = 'Kalenders';
$labels['task'] = 'Taken';
$labels['note'] = 'Notities';
$labels['configuration'] = 'Configuratie';
$labels['deletedevice'] = 'Delete device';
$labels['imageformat'] = 'Image format';
$labels['laxpiclabel'] = 'Sta PNG en GIF plaatjes toe';
$labels['nodevices'] = 'There are currently no devices registered.<br/><br/>In order to register a device, please connect it to the server first, using <a href="http://wiki.kolab.org/Setup_ActiveSync">the instructions in the Wiki</a>. Afterwards the device should become available for configuration here.';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['savingerror'] = 'Failed to save configuration';
$labels['notsupported'] = 'Your server does not support metadata/annotations';
$labels['devicedeleteconfirm'] = 'Do you really want to delete the configuration for this device?';
$labels['successfullydeleted'] = 'The device configuration was successfully removed';
$labels['devicenotfound'] = 'Unable to read device configuration';

?>
