<?php

$labels = array();
$labels['tabtitle'] = 'ActiveSync';
$labels['devices'] = 'Urządzenia';
$labels['devicealias'] = 'Nazwa urządzenia';
$labels['syncmode'] = 'Tryb synchronizacji';
$labels['modeauto'] = 'Ustaw automatycznie';
$labels['modeflat'] = 'Wymuś tryb płaski';
$labels['modefolder'] = 'Wymuś tryb folderu';
$labels['synchronize'] = 'Synchronizuj';
$labels['withalarms'] = 'Z alarmami';
$labels['syncsettings'] = 'Ustawienia synchronizacji';
$labels['deviceconfig'] = 'Konfiguracja urządzenia';
$labels['folderstosync'] = 'Foldery do synchronizacji';
$labels['mail'] = 'Poczta';
$labels['contact'] = 'Książki adresowe';
$labels['event'] = 'Kalendarze';
$labels['task'] = 'Zadania';
$labels['note'] = 'Notatki';
$labels['deletedevice'] = 'Usuń urządzenie';
$labels['imageformat'] = 'Format obrazka';
$labels['laxpiclabel'] = 'Zezwalaj na obrazki PNG i GIF';
$labels['introtext'] = 'Wybierz urządzenie do skonfigurowania';
$labels['nodevices'] = 'Obecnie brak zarejestrowanych urządzeń.<br/><br/>Aby zarejestrować urządzenie najpierw podłącz je do serwera według <a href="http://wiki.kolab.org/Z_push#Clients">instrukcji z Wiki</a>. Po tym procesie urządzenie powinno dać się skonfigurować tutaj.';
$labels['savingdata'] = 'Zapisywanie danych...';
$labels['savingerror'] = 'Nie udało się zapisać konfiguracji';
$labels['notsupported'] = 'Twój serwer nie obsługuje metadanych (metadata/annotations).';
$labels['devicedeleteconfirm'] = 'Czy na pewno chcesz usunąć konfigurację dla tego urządzenia?';
$labels['successfullydeleted'] = 'Konfiguracja urządzenia została pomyślnie usunięta.';

?>
