<?php

$labels = array();
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Устройства';
$labels['devicealias'] = 'Имя устройства';
$labels['syncmode'] = 'Режим синхронизации';
$labels['modeauto'] = 'Определить автоматически';
$labels['modeflat'] = 'Использовать плоский режим';
$labels['modefolder'] = 'Использовать режим директории';
$labels['synchronize'] = 'Синхронизовать';
$labels['withalarms'] = 'С напоминаниями';
$labels['syncsettings'] = 'Настройки синхронизации';
$labels['deviceconfig'] = 'Конфигурация устройства';
$labels['folderstosync'] = 'Каталоги для синхронизации';
$labels['mail'] = 'Почта';
$labels['contact'] = 'Адресные книги';
$labels['event'] = 'Календари';
$labels['task'] = 'Задачи';
$labels['note'] = 'Заметки';
$labels['configuration'] = 'Конфигурация';
$labels['deletedevice'] = 'Удалить устройство';
$labels['imageformat'] = 'Формат изображений';
$labels['laxpiclabel'] = 'Разрешить PNG и GIF изображения';
$labels['nodevices'] = 'У вас нет зарегистрированных устройств.<br/><br/>Для того, чтобы зарегистрировать устройство, подключите его к серверу, используя <a href="http://wiki.kolab.org/Z_push#Clients">инструкцию в Wiki</a>. После этого устройство должно стать доступным для конфигурации здесь.';
$labels['savingdata'] = 'Сохранение данных...';
$labels['savingerror'] = 'Не удалось сохранить конфигурацию';
$labels['notsupported'] = 'Ваш сервер не поддерживает метаданные/аннотации';
$labels['devicedeleteconfirm'] = 'Вы действительно хотите удалить конфигурацию для этого устройства?';
$labels['successfullydeleted'] = 'Конфигурация для устройства была успешно удалена.';
$labels['devicenotfound'] = 'Не удалось прочитать конфигурацию для устройства';

?>
